### ISSUE TITLE
Handle edges without name/type

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#119]
I found an interesting cornercase - if the square brackets are omitted from the query specification, the compiler throws an exception:

```
java.lang.NullPointerException
	at ingraph.cypher2relalg.RelalgBuilder$60.apply(RelalgBuilder.java:1772)
	at ingraph.cypher2relalg.RelalgBuilder$60.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at ingraph.cypher2relalg.RelalgBuilder._buildRelalg(RelalgBuilder.java:1775)
	at ingraph.cypher2relalg.RelalgBuilder.buildRelalg(RelalgBuilder.java:1940)
	at ingraph.cypher2relalg.RelalgBuilder$58.apply(RelalgBuilder.java:1743)
	at ingraph.cypher2relalg.RelalgBuilder$58.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at ingraph.cypher2relalg.util.Cypher2RelalgUtil.chainExpandOperators(Cypher2RelalgUtil.java:142)
	at ingraph.cypher2relalg.RelalgBuilder.buildRelalgFromPattern(RelalgBuilder.java:1748)
	at ingraph.cypher2relalg.RelalgBuilder._buildRelalg(RelalgBuilder.java:1718)
	at ingraph.cypher2relalg.RelalgBuilder.buildRelalg(RelalgBuilder.java:1934)
	at ingraph.cypher2relalg.RelalgBuilder$16.apply(RelalgBuilder.java:783)
	at ingraph.cypher2relalg.RelalgBuilder$16.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at ingraph.cypher2relalg.util.Cypher2RelalgUtil.buildLeftDeepTree(Cypher2RelalgUtil.java:69)
	at ingraph.cypher2relalg.RelalgBuilder$17.apply(RelalgBuilder.java:794)
	at ingraph.cypher2relalg.RelalgBuilder$17.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at ingraph.cypher2relalg.RelalgBuilder._buildRelalg(RelalgBuilder.java:797)
	at ingraph.cypher2relalg.RelalgBuilder.buildRelalg(RelalgBuilder.java:1938)
	at ingraph.cypher2relalg.RelalgBuilder$3$1.apply(RelalgBuilder.java:355)
	at ingraph.cypher2relalg.RelalgBuilder$3$1.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at ingraph.cypher2relalg.RelalgBuilder$3.apply(RelalgBuilder.java:358)
	at ingraph.cypher2relalg.RelalgBuilder$3.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.head(IteratorExtensions.java:140)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.head(IterableExtensions.java:119)
	at ingraph.cypher2relalg.RelalgBuilder._buildRelalgSubQuery(RelalgBuilder.java:365)
	at ingraph.cypher2relalg.RelalgBuilder._buildRelalg(RelalgBuilder.java:307)
	at ingraph.cypher2relalg.RelalgBuilder.buildRelalg(RelalgBuilder.java:1932)
	at ingraph.cypher2relalg.RelalgBuilder$1.apply(RelalgBuilder.java:228)
	at ingraph.cypher2relalg.RelalgBuilder$1.apply(RelalgBuilder.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at ingraph.cypher2relalg.RelalgBuilder.build(RelalgBuilder.java:231)
	at ingraph.cypher2relalg.Cypher2Relalg.processCypher(Cypher2Relalg.java:22)
	at ingraph.cypher2relalg.Cypher2Relalg.processString(Cypher2Relalg.java:17)
	at ingraph.optimization.test.Cypher2Relalg2Rete2TexTest.process(Cypher2Relalg2Rete2TexTest.java:40)
	at ingraph.optimization.test.ReteSandboxTest.why(ReteSandboxTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Example - this works:

```
MATCH (a)-[]->()
RETURN a
```

This does not work:

```
MATCH (a)-->()
RETURN a
```

**Comment by szarnyasg** [comment]
This bug reappeared in the new Catalyst-based compiler.
