### ISSUE TITLE
LDBC query 15 does not compile

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#128]
[LDBC query 15](https://github.com/FTSRG/ingraph/blob/master/queries/ldbc-snb-bi/query-15.cypher) does not compile:

```
MATCH
  (country:Country),
  (country)<-[:isPartOf]-(:City)<-[:isLocatedIn]-(somePerson:Person),
  (country)<-[:isPartOf]-(:City)<-[:isLocatedIn]-(friendOfSomePersion:Person),
  (somePerson)-[:knows]-(friendOfSomePerson)
WITH floor(count(friendOfSomePerson)/count(somePerson)) AS socialNormal
MATCH
  (country)<-[:isPartOf]-(:City)<-[:isLocatedIn]-(person:Person),
  (country)<-[:isPartOf]-(:City)<-[:isLocatedIn]-(friendOfPerson:Person),
  (person)-[:knows]-(friendOfPerson)
WITH socialNormal, person, count(friendOfPerson) AS count
WHERE socialNormal = count
RETURN person.id, count
ORDER BY person.id ASC
LIMIT 100
```

It throws the following exception:

> java.lang.RuntimeException: Unrecoverable error during compilation: So far we have seen a chain of , and now we reached relalg.impl.SelectionOperatorImpl. This does not match what we expected: relalg.TopOperator? relalg.SortOperator? relalg.DuplicateEliminationOperator? relalg.ProjectionOperator relalg.GroupingOperator?
>    at ingraph.logger.IngraphLogger.unrecoverableError(IngraphLogger.java:93)
>    at ingraph.cypher2relalg.util.Cypher2RelalgUtil.validateAndInjectLOJO(Cypher2RelalgUtil.java:449)
>    at ingraph.cypher2relalg.RelalgBuilder._buildRelalg(RelalgBuilder.java:319)

**Comment by szarnyasg** [comment]
The error is caused by this line:

```
WHERE socialNormal = count
```

If I uncomment this, the compiler works fine.
