### ISSUE TITLE
Support "metaqueries"

### ISSUE THREAD

**Issue by szarnyasg** [FTSRG/ingraph#53]
We should definitely support [`labels()`](https://neo4j.com/docs/developer-manual/current/cypher/#functions-labels) and [`type()`](https://neo4j.com/docs/developer-manual/current/cypher/#functions-type). I am not sure about [`properties()`](https://neo4j.com/docs/developer-manual/current/cypher/#functions-properties) and [`keys()`](https://neo4j.com/docs/developer-manual/current/cypher/#functions-keys).

**Comment by szarnyasg** [comment]
Some thoughts:
- `type()` returns a single string
- `labels()` returns a set of strings

For `type()`, the GetEdgesOperator should add the type to the edge as an additional element (string) in the tuple.
For `labels()`, either the GetVerticesOperator or the respective endpoint (source/target) of the GetEdgesOperator should add the labels as an additional element (list of strings) in the tuple.

**Comment by szarnyasg** [comment]
Also, `m:Message` style expressions should also be considered as metaqueries.

**Comment by szarnyasg** [comment]
`:NodeLabel`-style expressions now work, except when there are joins (expands or plain Cartesian products), in which case the schema inferencer just crashes because it does not propagate the variable either way.

```
MATCH (message2:Message) //, (x:X)
RETURN message2:Comment AS isComment
```

**Comment by marci543** [comment]
Related queries with the following exception:
>java.lang.AssertionError: assertion failed: Some properties were not propagated to either side of the join-like operator
>	at scala.Predef$.assert(Predef.scala:170)
>	at ingraph.compiler.plantransformers.NPlanToFPlan$.transform(NPlanToFPlan.scala:94)

LDBC SNB / Interactive / complex / 9
```
MATCH (:Person {id:19791209300143})-[:KNOWS]-(friend:Person)<-[:HAS_CREATOR]-(message)
WHERE message.creationDate <= 20121128000000000 AND (message:Post OR message:Comment)
RETURN
  friend.id AS personId,
  friend.firstName AS personFirstName,
  friend.lastName AS personLastName,
  message.id AS postOrCommentId,
  CASE exists(message.content)
    WHEN true THEN message.content
    ELSE message.imageFile
  END AS postOrCommentContent,
  message.creationDate AS postOrCommentCreationDate
ORDER BY postOrCommentCreationDate DESC, toInteger(postOrCommentId) ASC
LIMIT 20
```

TCK "MatchAcceptance2": "Multiple anonymous nodes in a pattern"
```
MATCH (a)<--()<--(b)-->()-->(c)
WHERE a:A
RETURN c
```

TCK "OptionalMatchAcceptance": "Return null when no matches due to label predicate in WHERE"
```
MATCH (n:Single)
OPTIONAL MATCH (n)-[r]-(m)
WHERE m:NonExistent
RETURN r
```
